In [1]:
import numpy as np

In [3]:
matrix1 = np.zeros((3,4))
matrix1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
matrix1 = np.array([[2,7,12,0],[3,9,3,4],[4,0,1,3]])
matrix1

array([[ 2,  7, 12,  0],
       [ 3,  9,  3,  4],
       [ 4,  0,  1,  3]])

In [24]:
zerosMatrix = np.zeros(10)
zerosMatrix

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
onesMatrix = np.ones((2,3,3))
onesMatrix

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [23]:
matrix2 = np.zeros((5,3))
matrix2
for x in matrix2:
    print(x+2)

[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
