In [ ]:
# khusus di jupyter note book catatan

# a = insert cell above
# b = insert cell bellow
# m = markdown
# y = code
# shift + enter = run

In [10]:
import numpy as np

In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.
You should consider upgrading via the 'C:\Users\muham\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [11]:
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

In [37]:
print(a+b)
print(a-b)

[1, 2, 3, 4, 5, 6, 7, 8]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [14]:
a_array = np.array(a)
b_array = np.array(b)

print(a_array + b_array)
print(a_array * b_array)

[ 6  8 10 12]
[ 5 12 21 32]


## LIST

In [17]:
iniList = ([1,2,3,4,5])
print(iniList)

[1, 2, 3, 4, 5]


In [18]:
arrayDuaDimensi = ([[1,2,3],[4,5,6]])
print(arrayDuaDimensi)

[[1, 2, 3], [4, 5, 6]]


In [36]:
iniList.shape

(5,)

In [20]:
arrayDuaDimensi = np.array([[1,2,3],[4,5,6]])
print(arrayDuaDimensi)

[[1 2 3]
 [4 5 6]]


In [21]:
iniList = np.array([1,2,3,4,5])
print(iniList)

[1 2 3 4 5]


## CREATE MATRIX ZEROS

In [26]:
# 1 dimension
zerosMatrix = np.zeros(5)
zerosMatrix

array([0., 0., 0., 0., 0.])

In [24]:
zerosMatrix = np.zeros((5,5))
print(zerosMatrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
zerosMatrix = np.zeros((5,5,2))
print(zerosMatrix)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [34]:
zerosMatrix.shape
zerosMatrix.size

5

## MATRIX ONE

In [35]:
matrixOnes = np.ones(5)
matrixOnes

array([1., 1., 1., 1., 1.])