In [1]:
import numpy as np

In [2]:
myArr = np.zeros((4,4), dtype = float)
myArr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
for i in range(0,np.size(myArr[0])):
    myArr[i]=i

myArr=myArr.T
print(myArr)

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [8]:
myArr = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11], [12,13,14,15]], dtype = float)
myArr


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [9]:
myArr = np.hsplit(myArr,2)
myArr

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]