In [20]:
import numpy as np

### 1. create a null vector / 1D array of size 10 and update fifth value to 11.

In [62]:
myArr = np.zeros((10), dtype = float)
print("Sebelum")
print(myArr)

myArr[4] = 11
print("Sesudah")
print(myArr)

Sebelum
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Sesudah
[ 0.  0.  0.  0. 11.  0.  0.  0.  0.  0.]


### 2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

In [64]:
myArr = np.array([[1,2,3],[4,5,6]], dtype = float)
print("Sebelum")
print(myArr)

myArrReshape = np.reshape(myArr,(3,2))
print("Sesudah")
print(myArrReshape)

Sebelum
[[1. 2. 3.]
 [4. 5. 6.]]
Sesudah
[[1. 2.]
 [3. 4.]
 [5. 6.]]


### 3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [85]:
myArr = np.ones((5,5), dtype = float)
print("Sebelum")
print(myArr)

print("Sesudah")
myArr[1:-1,1:-1] = 0
print(myArr)

Sebelum
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Sesudah
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### 4. Take a look at the following matrix. Access the 1, 1,2

In [87]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])
z

array([[[ 0,  1,  3],
        [ 5,  7,  9],
        [ 6,  8, 10]],

       [[ 0,  2,  4],
        [ 6,  8, 10],
        [ 0,  1,  3]],

       [[ 1,  1,  2],
        [ 5,  2,  9],
        [ 1,  3,  3]]])

In [97]:
z[2][0]

array([1, 1, 2])