In [2]:
from numpy import random

In [32]:
import numpy as np

In [5]:
random.randint(0,100, size=5)

array([ 8, 58, 24, 36, 99])

In [29]:
random.randint(0,100, size=(1,3,5))

array([[[69, 34, 61, 22,  3],
        [ 3,  0, 19, 28, 87],
        [56, 73,  9, 16, 20]]])

In [36]:
a = np.linspace(0, 2, 30)
a

array([0.        , 0.06896552, 0.13793103, 0.20689655, 0.27586207,
       0.34482759, 0.4137931 , 0.48275862, 0.55172414, 0.62068966,
       0.68965517, 0.75862069, 0.82758621, 0.89655172, 0.96551724,
       1.03448276, 1.10344828, 1.17241379, 1.24137931, 1.31034483,
       1.37931034, 1.44827586, 1.51724138, 1.5862069 , 1.65517241,
       1.72413793, 1.79310345, 1.86206897, 1.93103448, 2.        ])