In [2]:
import numpy as np

## arange

In [14]:
arangeOne = np.arange(5) #membuat array range seperti loop
arangeOne

array([0, 1, 2, 3, 4])

In [19]:
#contoh yang sama
for i in range(5):
    print(i)

0
1
2
3
4


In [16]:
# define berdasarkan range start ke akhir

arr = np.arange(5,10) # arguments: start, stop

arr


array([5, 6, 7, 8, 9])

In [22]:
# define range dengan step

arr = np.arange(1, 10, 2) # arguments: start, stop, step
arr

array([1, 3, 5, 7, 9])

In [23]:
arr = np.arange(-1, 1, 0.1) # arguments: start, stop, step

arr

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

## linspace

In [45]:
# using linspace, both end points ARE included
np.linspace(0, 10, 10) #Unlike arange that uses step, linspace uses the number of sample

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [40]:
a = np.linspace(0, 2, 5)
a

#linspace diatas digunakaan untuk mengegenerate sebuah array yang berisikan 5 buah bilangan dari 0 sampai dengan 5. Jarak antar bilangan dalam array ini adalah sama.

array([0. , 0.5, 1. , 1.5, 2. ])

In [44]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

## full

In [47]:
# full yaitu bila sebuah array bilangan konstan yang sama.
a = np.full((3, 3), 2)
a

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

## eye

In [52]:
# Matrix identitas berukuran m x n dapat dibuat dengan menggunakan eye.

a = np.eye(3, dtype = float)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random

In [54]:
from numpy import random

In [110]:
random.rand()

0.46448651228094584

In [101]:
a = np.random.random((3,2))
a

array([[0.81903865, 0.86867312],
       [0.65057168, 0.29006665],
       [0.857319  , 0.36495588]])

In [116]:
random.rand(5,5)

array([[0.91184058, 0.40114962, 0.96979411, 0.07155024, 0.74327074],
       [0.53943798, 0.74600026, 0.70434   , 0.95578415, 0.7656031 ],
       [0.12768944, 0.09876388, 0.60124237, 0.37699097, 0.69118951],
       [0.91210677, 0.68421452, 0.46230349, 0.35015571, 0.21330147],
       [0.87139497, 0.55768662, 0.08951245, 0.82198552, 0.7817851 ]])

In [120]:
a = random.rand(3,2)
a

array([[0.51894031, 0.22294024],
       [0.68467283, 0.61142727],
       [0.15387804, 0.78555816]])

In [121]:
a.dtype

dtype('float64')

In [122]:
x = np.ones(2, dtype = np.int64)
x

array([1, 1], dtype=int64)

In [142]:
random.randint(100)

13

In [152]:
random.randint(2,10, size=5)

array([9, 5, 4, 6, 3])

In [156]:
random.randint(2, 10, size=(5,3,3))

array([[[5, 8, 7],
        [8, 2, 9],
        [6, 3, 7]],

       [[9, 4, 3],
        [9, 7, 9],
        [3, 2, 8]],

       [[3, 3, 7],
        [2, 3, 2],
        [6, 3, 8]],

       [[4, 5, 3],
        [5, 3, 4],
        [2, 9, 8]],

       [[5, 2, 3],
        [7, 3, 4],
        [8, 6, 2]]])

## Adding, removing, and sorting elements

In [157]:
myArr = np.arange(10)
myArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [158]:
# append
np.append(myArr, (10,11,12))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [159]:
myArr = np.array([[1,2,3],[4,5,6]])
myArr

array([[1, 2, 3],
       [4, 5, 6]])

In [163]:
np.append(myArr, [[2,1,1]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [2, 1, 1]])

In [169]:
x = np.array([[1,2,3], [1,1,1]])
y = np.array([[4,5,6], [2,2,2]])
z = np.concatenate((x,y), axis=1)

z

array([[1, 2, 3, 4, 5, 6],
       [1, 1, 1, 2, 2, 2]])

In [213]:
# sorting np.sort()

arr= np.array([2,1,5,3,7,4,6,8])
# np.sort(arr)
arr.sort()
arr


array([1, 2, 3, 4, 5, 6, 7, 8])

In [198]:
a = np.random.random(3)
print(a)
a.sort()
print(a)

[0.24832545 0.80699229 0.19806401]
[0.19806401 0.24832545 0.80699229]


## concatenate array

In [15]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(a)

np.concatenate((a,b))

[1 2 3 4]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
print(x)

np.concatenate((x,y), axis=0) #if axis = None, then arrays are flatten before use

[[1 2]
 [3 4]]


array([[1, 2],
       [3, 4],
       [5, 6]])