In [2]:
import numpy as np

In [3]:
a = np.arange(2,11).reshape(3,3)
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [4]:
x = np.array([[0, 1, 3], [5, 7, 9]])
y = np.array([[0, 2, 4], [6, 8, 10]])
x = np.concatenate((x, y), axis = 1)
print(x)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]
